modLoader="javafml"
loaderVersion="[31,)" #mandatory (26 is current forge version)
license="MIT"

[[mods]]
modId="parkour_recorder"
version="1.1.1.0-1.16.5"
displayName="Parkour Recorder"
logoFile="logo.png"
description='''
A Minecraft mod that allows you to record and playback parkour sessions.
'''
